name: Whitespace check

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Whitespace check
      run: |
        git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
        git diff ${{ github.base_ref }} >/tmp/diff1.txt
        git diff -w ${{ github.base_ref }} >/tmp/diff2.txt
        diff /tmp/diff1.txt /tmp/diff2.txt >/dev/null
